#13: Join support.
exasol/exasol-virtual-schema-lua pull request #14
Opened 2022-07-28 12:41 UTC by redcatbear

Closes #13.

2022-07-28 14:38 UTC, kaklakariada requested changes

2022-07-28 14:38 UTC, kaklakariada commented on doc/changes/changes_0.2.0.md
> +# Exasol Row Level Security (Lua) 0.2.0, released 2022-07-27
```suggestion
# Exasol Row Level Security (Lua) 0.2.0, released 2022-07-28
```
or -29?

2022-07-28 14:38 UTC, kaklakariada commented on src/test/java/com/exasol/SelectIT.java
> +    }
👍 Tests are easy to understand!

2022-07-28 14:38 UTC, kaklakariada commented on src/main/lua/exasolvs/adapter_capabilities.lua
> +    "ORDER_BY_EXPRESSION", "JOIN", "JOIN_CONDITION_EQUI", "JOIN_TYPE_INNER",  "JOIN_TYPE_FULL_OUTER",
What does `JOIN_CONDITION_EQUI` mean? Do we need an integration test for that?

2022-07-28 14:38 UTC, kaklakariada commented on src/main/lua/exasolvs/QueryRewriter.lua
> +            log.debug("Extending: " .. element.name)
```suggestion
            log.debug("Extending: %s", element.name)
```
More efficient?

2022-07-28 14:38 UTC, kaklakariada commented on src/main/lua/exasolvs/QueryRewriter.lua
> +local function extend_query_element_with_source_schema(element, source_schema_id)
Do we need unit tests for this function or are the integration tests enough?

2022-07-29 06:34 UTC, redcatbear commented on src/main/lua/exasolvs/adapter_capabilities.lua
> +    "ORDER_BY_EXPRESSION", "JOIN", "JOIN_CONDITION_EQUI", "JOIN_TYPE_INNER",  "JOIN_TYPE_FULL_OUTER",
That's a fancy way of saying you support a "=" in the join condition.

2022-07-29 08:49 UTC, redcatbear commented on doc/changes/changes_0.2.0.md
> +# Exasol Row Level Security (Lua) 0.2.0, released 2022-07-27
Updated.

2022-07-29 08:50 UTC, redcatbear commented on src/main/lua/exasolvs/adapter_capabilities.lua
> +    "ORDER_BY_EXPRESSION", "JOIN", "JOIN_CONDITION_EQUI", "JOIN_TYPE_INNER",  "JOIN_TYPE_FULL_OUTER",
You reminded me that I forgot the complex join condition capability. Added that and a matching integration test.

2022-07-29 08:56 UTC, redcatbear commented on src/main/lua/exasolvs/QueryRewriter.lua
> +            log.debug("Extending: " .. element.name)
Fixed.

2022-07-29 09:25 UTC, redcatbear commented on src/main/lua/exasolvs/QueryRewriter.lua
> +local function extend_query_element_with_source_schema(element, source_schema_id)
A unit test helps locate errors better, so I think keeping both is worth it. Also it showcases what this workaround is for.

2022-07-29 09:28 UTC, kaklakariada commented on src/main/lua/exasolvs/adapter_capabilities.lua
> +    "ORDER_BY_EXPRESSION", "JOIN", "JOIN_CONDITION_EQUI", "JOIN_TYPE_INNER",  "JOIN_TYPE_FULL_OUTER",
:-) 👍

2022-07-29 09:33 UTC, kaklakariada approved these changes

2022-07-29 09:34 UTC, merged