#8: Performance test comparing original query with VS query
exasol/exasol-virtual-schema-lua pull request #22
Opened 2022-10-05 13:59 UTC by redcatbear

Closes #8.

2022-10-06 07:21 UTC, kaklakariada requested changes

2022-10-07 05:40 UTC, redcatbear commented on pom.xml
> +        <sonar.coverage.jacoco.xmlReportPaths>target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
Removed.

2022-10-07 07:54 UTC, redcatbear commented on spec/build_preconditions_spec.lua
> +        end)
Moved loading to first test and introduced assumptions in the follow-up tests.

2022-10-10 07:30 UTC, kaklakariada approved these changes

2022-10-18 06:44 UTC, kaklakariada approved these changes

2022-10-18 07:01 UTC, merged