#20: Introduced abstraction to allow for different metadata readers.
exasol/exasol-virtual-schema-lua pull request #30
Opened 2023-02-16 11:05 UTC by redcatbear

Closes #20.

2023-02-17 08:47 UTC, kaklakariada requested changes

2023-02-17 08:47 UTC, kaklakariada commented on src/main/lua/exasolvs/ExasolAdapter.lua
> +        log.debug("Creating a metadata reader  that reads directly from the local database")
```suggestion
        log.debug("Creating a metadata reader that reads directly from the local database")
```

2023-02-17 08:47 UTC, kaklakariada commented on src/main/lua/exasolvs/ExasolAdapter.lua
> +    local connection_id = properties:get_connection_name()
Inconsistent naming of variable and method name: id vs. name

2023-02-17 08:47 UTC, kaklakariada commented on src/main/lua/exasolvs/MetadataReaderFactory.lua
> +--- Create a metadata that reads the metadata from the local database.
```suggestion
--- Create a metadata reader that reads the metadata from the local database.
```

2023-02-17 08:47 UTC, kaklakariada commented on src/main/lua/exasolvs/MetadataReaderFactory.lua
> +--- Create a metadata that reads the metadata from the local database.
```suggestion
--- Create a metadata reader that reads the metadata from a remote database.
```

2023-02-17 08:47 UTC, kaklakariada commented on src/main/lua/exasolvs/RemoteMetadataReader.lua
> +        return true, rows
Does it make sense to have two return values when errors are raised anyway, and the first return value is always `true`?

2023-02-17 08:47 UTC, kaklakariada commented on src/test/java/com/exasol/AbstractLuaVirtualSchemaIT.java
> +        Files.writeString(Path.of("/tmp", adapterScript.getName() + ".lua"), adapterScript.getContent());
```suggestion
```

2023-02-27 08:42 UTC, redcatbear commented on doc/model/diagrams/sequence/seq_read_remote_schema_metadata.plantuml
> +    alt table wanted
Wanted is more that not excluded. In case of RLS (which we plan to merge with this) control tables are also not visible in the VS.

2023-02-27 08:50 UTC, redcatbear commented on doc/changes/changes_0.4.0.md
> +In this release we added support for connecting to a remote Exasol database. Note that TLS is not yet supported, because at the time of this release the required Lua libraries were not yet available
Correct. I improved the disclaimer.

2023-02-27 08:54 UTC, redcatbear commented on spec/exasol/validator_spec.lua
> +                                .. "'.*")
Done.

2023-02-27 08:56 UTC, redcatbear commented on spec/exasolvs/ConnectionReader_spec.lua
> +    it("reads a connection definition with host, port, user and password", function()
Done.

2023-02-27 09:03 UTC, redcatbear commented on spec/exasolvs/MetadataReaderFactory_spec.lua
> +        assert.are_same("the_connection", reader._connection_id)
Done.

2023-02-27 09:06 UTC, redcatbear commented on spec/exasol/validator_spec.lua
> +            {"1_starts_with_a_number", 1}
Done.

2023-02-27 09:14 UTC, redcatbear commented on spec/exasol/validator_spec.lua
> +describe("validator", function()
Done.

2023-02-27 09:17 UTC, redcatbear commented on src/main/lua/exasolvs/ExasolAdapter.lua
> +    local connection_id = properties:get_connection_name()
This is owed to the name of the property.

2023-02-27 11:46 UTC, redcatbear commented on src/main/lua/exasolvs/RemoteMetadataReader.lua
> +        return true, rows
Good point. Returned `false` and text instead.

2023-02-27 15:33 UTC, kaklakariada approved these changes

2023-03-01 09:52 UTC, kaklakariada approved these changes

2023-03-01 09:55 UTC, merged