#21: Import
exasol/exasol-virtual-schema-lua pull request #33
Opened 2023-03-09 11:14 UTC by redcatbear

Closes #21.

2023-03-10 05:34 UTC, kaklakariada requested changes

2023-03-10 05:34 UTC, kaklakariada commented on spec/exasolvs/ConnectionReader_spec.lua
> +                "example.org:333/f1db0bd29facca504240c859d1021f0f169106713052952c83a3407d4ca647ef",
According to https://docs.exasol.com/db/latest/connect_exasol/drivers/jdbc.htm#ExasolURL the fingerprint is between host and port.

Would it be possible to have a separate parameter (e.g. `;fingerprint=...` for the fingerprint? I don't like this syntax ;)

2023-03-10 05:34 UTC, kaklakariada commented on spec/exasolvs/LocalQueryRewriter_spec.lua
>                  "Unable to rewrite query because it was <nil>.", 1, true)
Does the error message contain an error code? Would it be possible to include it in the assertion?
Same for the following test.

2023-03-10 05:34 UTC, kaklakariada commented on spec/exasolvs/QueryRewriterFactory_spec.lua
> +require("busted.runner")()
Would it be possible to extract the first (or both) lines into a separate file to avoid duplication?

2023-03-10 05:34 UTC, kaklakariada commented on spec/exasolvs/RemoteQueryRewriter_spec.lua
> +    it("rewrites a query with an unprotected table", function()
What does 'unprotected' mean in this context?

2023-03-10 05:34 UTC, kaklakariada commented on src/main/lua/exasolvs/AbstractQueryRewriter.lua
> +--- Create a new instance of a <code>QueryRewriter</code>.
```suggestion
--- Create a new instance of a `QueryRewriter`.
```
❓

2023-03-10 05:34 UTC, kaklakariada commented on src/main/lua/exasolvs/ConnectionReader.lua
> +    local slash_location = string.find(address, "/", colon_location + 1, true) or 0
See note in test: fingerprint comes before port.

2023-03-10 05:34 UTC, kaklakariada commented on src/main/lua/exasolvs/ConnectionReader.lua
> +            return host, EXASOL_DEFAULT_PORT
```suggestion
            return host, EXASOL_DEFAULT_PORT, nil
```
❓

2023-03-10 05:34 UTC, kaklakariada commented on src/main/lua/exasolvs/ConnectionReader.lua
> +            return host, port
```suggestion
            return host, port, nil
```
❓

2023-03-10 05:34 UTC, kaklakariada commented on src/main/lua/exasolvs/LocalQueryRewriter.lua
> +--- This class rewrites the query.
```suggestion
--- This class rewrites the query for the local database.
```

2023-03-10 05:34 UTC, kaklakariada commented on src/main/lua/exasolvs/LocalQueryRewriter.lua
> +--- Create a new instance of a <code>LocalQueryRewriter</code>.
```suggestion
--- Create a new instance of a `LocalQueryRewriter`.
```

2023-03-10 05:34 UTC, kaklakariada commented on src/main/lua/exasolvs/QueryRewriterFactory.lua
> +-- statement (remote) or a `SELECT` (local).
```suggestion
--- Create a query rewriter that produces local or remote queries.
-- Depending on whether a remote connection is supplied or not creates either a rewriter that produces an `IMPORT`
-- statement (remote) or a `SELECT` statement (local).
```

2023-03-10 05:34 UTC, kaklakariada commented on src/main/lua/exasolvs/RemoteQueryRewriter.lua
> +--- This class rewrites the query.
```suggestion
--- This class rewrites the query for a remote database.
```

2023-03-10 05:34 UTC, kaklakariada commented on src/main/lua/exasolvs/RemoteQueryRewriter.lua
> +--- Create a new instance of a <code>RemoteQueryRewriter</code>.
```suggestion
--- Create a new instance of a `RemoteQueryRewriter`.
```

2023-03-10 05:34 UTC, kaklakariada commented on src/main/lua/exasolvs/RemoteQueryRewriter.lua
> +-- @param connection_id name of the connection object that defines the details of the connection to the remote Exasol
```suggestion
-- @param connection_id name of the connection object that defines the details of the connection to the remote Exasol
```
Is this the connection **id** or a connection **object**? Either rename the parameter or update the comment.

2023-03-10 05:34 UTC, kaklakariada commented on src/test/java/com/exasol/ImportIT.java
> +    //  [itest -> dsn~remote-push-down~0]
```suggestion
    // [itest -> dsn~remote-push-down~0]
```

2023-03-10 05:34 UTC, kaklakariada commented on src/test/java/com/exasol/ImportIT.java
> +    //  [itest -> dsn~remote-push-down~0]
```suggestion
    // [itest -> dsn~remote-push-down~0]
```

2023-03-10 05:34 UTC, kaklakariada commented on src/test/java/com/exasol/ImportIT.java
> +    //  [itest -> dsn~remote-push-down~0]
```suggestion
    // [itest -> dsn~remote-push-down~0]
```

2023-03-10 05:34 UTC, kaklakariada commented on src/test/java/com/exasol/ImportIT.java
> +                table().row(1).row(2).matches(NO_JAVA_TYPE_CHECK));
Tests contain lot's of duplicate code, so it's hard to see what is the actual test. Can we extract common parts?

Trino's tests are quite readable and compact, e.g.: https://github.com/trinodb/trino/blob/master/plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java#L120

2023-03-13 07:42 UTC, redcatbear commented on doc/model/diagrams/sequence/seq_pushdown.plantuml
> +alt connection provided
As discussed offline, there are imporant differences. So we will keep this as is.

2023-03-13 07:46 UTC, redcatbear commented on spec/exasolvs/QueryRewriterFactory_spec.lua
> +require("busted.runner")()
It's only one line of duplication and that is owed to the non-standard directory layout of the mixed Lua / Java project. Also I think that the runner needs the right module as context.

2023-03-13 07:49 UTC, redcatbear commented on spec/exasolvs/RemoteQueryRewriter_spec.lua
> +    it("rewrites a query with an unprotected table", function()
That is shared logic from RLS. I plan to join the two projects soon, so I though, I don't let them diverge too much.

2023-03-13 12:11 UTC, redcatbear commented on spec/exasolvs/LocalQueryRewriter_spec.lua
>                  "Unable to rewrite query because it was <nil>.", 1, true)
As discussed together, we will keep that as is.

2023-03-13 12:12 UTC, redcatbear commented on spec/exasolvs/ConnectionReader_spec.lua
> +                "example.org:333/f1db0bd29facca504240c859d1021f0f169106713052952c83a3407d4ca647ef",
Good point: https://docs.exasol.com/db/latest/connect_exasol/drivers/jdbc.htm?Highlight=fingerprint#ExasolURL

2023-03-13 12:23 UTC, redcatbear commented on spec/exasolvs/ConnectionReader_spec.lua
> +                "example.org:333/f1db0bd29facca504240c859d1021f0f169106713052952c83a3407d4ca647ef",
Fixed.

2023-03-13 12:23 UTC, redcatbear commented on src/main/lua/exasolvs/ConnectionReader.lua
> +    local slash_location = string.find(address, "/", colon_location + 1, true) or 0
Fixed.

2023-03-13 14:39 UTC, kaklakariada submitted a review, later dismissed

2023-03-14 07:48 UTC, kaklakariada approved these changes

2023-03-14 07:48 UTC, merged